SCR_PlaceableEntitiesRegistry {
 m_sAddon "25thCRX"
 m_sSourceDirectory ""
 m_bExposed 1
 m_Prefabs {
  "{841779BF689F6FB5}Prefabs/E_DCO_TaskZone.et"
  "{A524C110BDE25731}Prefabs/E_DCO_TaskZone_Ambush.et"
  "{43C3E316165CD677}Prefabs/E_DCO_TaskZone_AmbushKillZone.et"
  "{1D28FFA184C2D8EC}Prefabs/E_DCO_TaskZone_Defend.et"
  "{46124C5C81890FC2}Prefabs/E_DCO_TaskZone_Reinforce.et"
  "{0C71DD0778ADF425}Prefabs/E_DCO_ObjectiveZone.et"
 }
}
